name: Build and SonarCloud

on:
  push:
    branches:
      - yenkhai-GenerateReportYml-create

jobs:
  build-and-sonarcloud:
    name: Build and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with: # test change
          java-version: '11' # Adjust the version as needed
          distribution: 'microsoft'

      - name: Build with Ant
        run: ant # Replace 'build' with your actual Ant build target

      - name: Run Tests with Ant
        run: ant test # Replace 'test' with your actual Ant test target

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
